apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment-producer.yaml
  - deployment-categorizer.yaml
  - deployment-writer.yaml
  - cronjob-uncategorized-metrics.yaml
  - prometheusrule.yaml
